language: node_js
node_js:
  - 6
install:
  - npm install -g particle-cli
  - 'mkdir ~/.particle && echo {\"access_token\": \"$PARTICLE_TOKEN\"} > ~/.particle/particle.config.json'
script:
  - ./compile_examples.sh
